// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppProtoc.proto

package com.kindroid.security.util;

public final class AppProtoc {
  private AppProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class App extends
      com.google.protobuf.GeneratedMessage {
    // Use App.newBuilder() to construct.
    private App() {
      initFields();
    }
    private App(boolean noInit) {}
    
    private static final App defaultInstance;
    public static App getDefaultInstance() {
      return defaultInstance;
    }
    
    public App getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kindroid.security.util.AppProtoc.internal_static_com_kindroid_security_util_App_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kindroid.security.util.AppProtoc.internal_static_com_kindroid_security_util_App_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public boolean hasTitle() { return hasTitle; }
    public java.lang.String getTitle() { return title_; }
    
    // optional string author = 3;
    public static final int AUTHOR_FIELD_NUMBER = 3;
    private boolean hasAuthor;
    private java.lang.String author_ = "";
    public boolean hasAuthor() { return hasAuthor; }
    public java.lang.String getAuthor() { return author_; }
    
    // optional int32 versioncode = 4;
    public static final int VERSIONCODE_FIELD_NUMBER = 4;
    private boolean hasVersioncode;
    private int versioncode_ = 0;
    public boolean hasVersioncode() { return hasVersioncode; }
    public int getVersioncode() { return versioncode_; }
    
    // optional string versionname = 5;
    public static final int VERSIONNAME_FIELD_NUMBER = 5;
    private boolean hasVersionname;
    private java.lang.String versionname_ = "";
    public boolean hasVersionname() { return hasVersionname; }
    public java.lang.String getVersionname() { return versionname_; }
    
    // optional int32 ratecount = 6;
    public static final int RATECOUNT_FIELD_NUMBER = 6;
    private boolean hasRatecount;
    private int ratecount_ = 0;
    public boolean hasRatecount() { return hasRatecount; }
    public int getRatecount() { return ratecount_; }
    
    // optional double price = 7;
    public static final int PRICE_FIELD_NUMBER = 7;
    private boolean hasPrice;
    private double price_ = 0D;
    public boolean hasPrice() { return hasPrice; }
    public double getPrice() { return price_; }
    
    // optional string priceUnit = 8;
    public static final int PRICEUNIT_FIELD_NUMBER = 8;
    private boolean hasPriceUnit;
    private java.lang.String priceUnit_ = "";
    public boolean hasPriceUnit() { return hasPriceUnit; }
    public java.lang.String getPriceUnit() { return priceUnit_; }
    
    // optional string description = 9;
    public static final int DESCRIPTION_FIELD_NUMBER = 9;
    private boolean hasDescription;
    private java.lang.String description_ = "";
    public boolean hasDescription() { return hasDescription; }
    public java.lang.String getDescription() { return description_; }
    
    // optional int32 downloadsCount = 10;
    public static final int DOWNLOADSCOUNT_FIELD_NUMBER = 10;
    private boolean hasDownloadsCount;
    private int downloadsCount_ = 0;
    public boolean hasDownloadsCount() { return hasDownloadsCount; }
    public int getDownloadsCount() { return downloadsCount_; }
    
    // optional int32 lastmonth_downloadscount = 11;
    public static final int LASTMONTH_DOWNLOADSCOUNT_FIELD_NUMBER = 11;
    private boolean hasLastmonthDownloadscount;
    private int lastmonthDownloadscount_ = 0;
    public boolean hasLastmonthDownloadscount() { return hasLastmonthDownloadscount; }
    public int getLastmonthDownloadscount() { return lastmonthDownloadscount_; }
    
    // optional int32 lastweek_downloadscount = 12;
    public static final int LASTWEEK_DOWNLOADSCOUNT_FIELD_NUMBER = 12;
    private boolean hasLastweekDownloadscount;
    private int lastweekDownloadscount_ = 0;
    public boolean hasLastweekDownloadscount() { return hasLastweekDownloadscount; }
    public int getLastweekDownloadscount() { return lastweekDownloadscount_; }
    
    // optional int32 installSize = 13;
    public static final int INSTALLSIZE_FIELD_NUMBER = 13;
    private boolean hasInstallSize;
    private int installSize_ = 0;
    public boolean hasInstallSize() { return hasInstallSize; }
    public int getInstallSize() { return installSize_; }
    
    // optional string packageName = 14;
    public static final int PACKAGENAME_FIELD_NUMBER = 14;
    private boolean hasPackageName;
    private java.lang.String packageName_ = "";
    public boolean hasPackageName() { return hasPackageName; }
    public java.lang.String getPackageName() { return packageName_; }
    
    // optional string category = 15;
    public static final int CATEGORY_FIELD_NUMBER = 15;
    private boolean hasCategory;
    private java.lang.String category_ = "";
    public boolean hasCategory() { return hasCategory; }
    public java.lang.String getCategory() { return category_; }
    
    // optional int32 screenshotsCount = 16;
    public static final int SCREENSHOTSCOUNT_FIELD_NUMBER = 16;
    private boolean hasScreenshotsCount;
    private int screenshotsCount_ = 0;
    public boolean hasScreenshotsCount() { return hasScreenshotsCount; }
    public int getScreenshotsCount() { return screenshotsCount_; }
    
    // optional string pathguid = 17;
    public static final int PATHGUID_FIELD_NUMBER = 17;
    private boolean hasPathguid;
    private java.lang.String pathguid_ = "";
    public boolean hasPathguid() { return hasPathguid; }
    public java.lang.String getPathguid() { return pathguid_; }
    
    // optional bytes iconData = 18;
    public static final int ICONDATA_FIELD_NUMBER = 18;
    private boolean hasIconData;
    private com.google.protobuf.ByteString iconData_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasIconData() { return hasIconData; }
    public com.google.protobuf.ByteString getIconData() { return iconData_; }
    
    // optional string downloadUrl = 19;
    public static final int DOWNLOADURL_FIELD_NUMBER = 19;
    private boolean hasDownloadUrl;
    private java.lang.String downloadUrl_ = "";
    public boolean hasDownloadUrl() { return hasDownloadUrl; }
    public java.lang.String getDownloadUrl() { return downloadUrl_; }
    
    // optional int32 partnerID = 20;
    public static final int PARTNERID_FIELD_NUMBER = 20;
    private boolean hasPartnerID;
    private int partnerID_ = 0;
    public boolean hasPartnerID() { return hasPartnerID; }
    public int getPartnerID() { return partnerID_; }
    
    // optional int32 foreignID = 21;
    public static final int FOREIGNID_FIELD_NUMBER = 21;
    private boolean hasForeignID;
    private int foreignID_ = 0;
    public boolean hasForeignID() { return hasForeignID; }
    public int getForeignID() { return foreignID_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasTitle()) {
        output.writeString(2, getTitle());
      }
      if (hasAuthor()) {
        output.writeString(3, getAuthor());
      }
      if (hasVersioncode()) {
        output.writeInt32(4, getVersioncode());
      }
      if (hasVersionname()) {
        output.writeString(5, getVersionname());
      }
      if (hasRatecount()) {
        output.writeInt32(6, getRatecount());
      }
      if (hasPrice()) {
        output.writeDouble(7, getPrice());
      }
      if (hasPriceUnit()) {
        output.writeString(8, getPriceUnit());
      }
      if (hasDescription()) {
        output.writeString(9, getDescription());
      }
      if (hasDownloadsCount()) {
        output.writeInt32(10, getDownloadsCount());
      }
      if (hasLastmonthDownloadscount()) {
        output.writeInt32(11, getLastmonthDownloadscount());
      }
      if (hasLastweekDownloadscount()) {
        output.writeInt32(12, getLastweekDownloadscount());
      }
      if (hasInstallSize()) {
        output.writeInt32(13, getInstallSize());
      }
      if (hasPackageName()) {
        output.writeString(14, getPackageName());
      }
      if (hasCategory()) {
        output.writeString(15, getCategory());
      }
      if (hasScreenshotsCount()) {
        output.writeInt32(16, getScreenshotsCount());
      }
      if (hasPathguid()) {
        output.writeString(17, getPathguid());
      }
      if (hasIconData()) {
        output.writeBytes(18, getIconData());
      }
      if (hasDownloadUrl()) {
        output.writeString(19, getDownloadUrl());
      }
      if (hasPartnerID()) {
        output.writeInt32(20, getPartnerID());
      }
      if (hasForeignID()) {
        output.writeInt32(21, getForeignID());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasTitle()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getTitle());
      }
      if (hasAuthor()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getAuthor());
      }
      if (hasVersioncode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getVersioncode());
      }
      if (hasVersionname()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getVersionname());
      }
      if (hasRatecount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, getRatecount());
      }
      if (hasPrice()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, getPrice());
      }
      if (hasPriceUnit()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getPriceUnit());
      }
      if (hasDescription()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getDescription());
      }
      if (hasDownloadsCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, getDownloadsCount());
      }
      if (hasLastmonthDownloadscount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, getLastmonthDownloadscount());
      }
      if (hasLastweekDownloadscount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, getLastweekDownloadscount());
      }
      if (hasInstallSize()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, getInstallSize());
      }
      if (hasPackageName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(14, getPackageName());
      }
      if (hasCategory()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(15, getCategory());
      }
      if (hasScreenshotsCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, getScreenshotsCount());
      }
      if (hasPathguid()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(17, getPathguid());
      }
      if (hasIconData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(18, getIconData());
      }
      if (hasDownloadUrl()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(19, getDownloadUrl());
      }
      if (hasPartnerID()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, getPartnerID());
      }
      if (hasForeignID()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(21, getForeignID());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.kindroid.security.util.AppProtoc.App parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.App parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.App parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.App parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.App parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.App parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.App parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.security.util.AppProtoc.App parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.security.util.AppProtoc.App parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.App parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kindroid.security.util.AppProtoc.App prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.kindroid.security.util.AppProtoc.App result;
      
      // Construct using com.kindroid.security.util.AppProtoc.App.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.kindroid.security.util.AppProtoc.App();
        return builder;
      }
      
      protected com.kindroid.security.util.AppProtoc.App internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.kindroid.security.util.AppProtoc.App();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kindroid.security.util.AppProtoc.App.getDescriptor();
      }
      
      public com.kindroid.security.util.AppProtoc.App getDefaultInstanceForType() {
        return com.kindroid.security.util.AppProtoc.App.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.kindroid.security.util.AppProtoc.App build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.kindroid.security.util.AppProtoc.App buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.kindroid.security.util.AppProtoc.App buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.kindroid.security.util.AppProtoc.App returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kindroid.security.util.AppProtoc.App) {
          return mergeFrom((com.kindroid.security.util.AppProtoc.App)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.kindroid.security.util.AppProtoc.App other) {
        if (other == com.kindroid.security.util.AppProtoc.App.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasAuthor()) {
          setAuthor(other.getAuthor());
        }
        if (other.hasVersioncode()) {
          setVersioncode(other.getVersioncode());
        }
        if (other.hasVersionname()) {
          setVersionname(other.getVersionname());
        }
        if (other.hasRatecount()) {
          setRatecount(other.getRatecount());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasPriceUnit()) {
          setPriceUnit(other.getPriceUnit());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasDownloadsCount()) {
          setDownloadsCount(other.getDownloadsCount());
        }
        if (other.hasLastmonthDownloadscount()) {
          setLastmonthDownloadscount(other.getLastmonthDownloadscount());
        }
        if (other.hasLastweekDownloadscount()) {
          setLastweekDownloadscount(other.getLastweekDownloadscount());
        }
        if (other.hasInstallSize()) {
          setInstallSize(other.getInstallSize());
        }
        if (other.hasPackageName()) {
          setPackageName(other.getPackageName());
        }
        if (other.hasCategory()) {
          setCategory(other.getCategory());
        }
        if (other.hasScreenshotsCount()) {
          setScreenshotsCount(other.getScreenshotsCount());
        }
        if (other.hasPathguid()) {
          setPathguid(other.getPathguid());
        }
        if (other.hasIconData()) {
          setIconData(other.getIconData());
        }
        if (other.hasDownloadUrl()) {
          setDownloadUrl(other.getDownloadUrl());
        }
        if (other.hasPartnerID()) {
          setPartnerID(other.getPartnerID());
        }
        if (other.hasForeignID()) {
          setForeignID(other.getForeignID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 18: {
              setTitle(input.readString());
              break;
            }
            case 26: {
              setAuthor(input.readString());
              break;
            }
            case 32: {
              setVersioncode(input.readInt32());
              break;
            }
            case 42: {
              setVersionname(input.readString());
              break;
            }
            case 48: {
              setRatecount(input.readInt32());
              break;
            }
            case 57: {
              setPrice(input.readDouble());
              break;
            }
            case 66: {
              setPriceUnit(input.readString());
              break;
            }
            case 74: {
              setDescription(input.readString());
              break;
            }
            case 80: {
              setDownloadsCount(input.readInt32());
              break;
            }
            case 88: {
              setLastmonthDownloadscount(input.readInt32());
              break;
            }
            case 96: {
              setLastweekDownloadscount(input.readInt32());
              break;
            }
            case 104: {
              setInstallSize(input.readInt32());
              break;
            }
            case 114: {
              setPackageName(input.readString());
              break;
            }
            case 122: {
              setCategory(input.readString());
              break;
            }
            case 128: {
              setScreenshotsCount(input.readInt32());
              break;
            }
            case 138: {
              setPathguid(input.readString());
              break;
            }
            case 146: {
              setIconData(input.readBytes());
              break;
            }
            case 154: {
              setDownloadUrl(input.readString());
              break;
            }
            case 160: {
              setPartnerID(input.readInt32());
              break;
            }
            case 168: {
              setForeignID(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional string title = 2;
      public boolean hasTitle() {
        return result.hasTitle();
      }
      public java.lang.String getTitle() {
        return result.getTitle();
      }
      public Builder setTitle(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder clearTitle() {
        result.hasTitle = false;
        result.title_ = getDefaultInstance().getTitle();
        return this;
      }
      
      // optional string author = 3;
      public boolean hasAuthor() {
        return result.hasAuthor();
      }
      public java.lang.String getAuthor() {
        return result.getAuthor();
      }
      public Builder setAuthor(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAuthor = true;
        result.author_ = value;
        return this;
      }
      public Builder clearAuthor() {
        result.hasAuthor = false;
        result.author_ = getDefaultInstance().getAuthor();
        return this;
      }
      
      // optional int32 versioncode = 4;
      public boolean hasVersioncode() {
        return result.hasVersioncode();
      }
      public int getVersioncode() {
        return result.getVersioncode();
      }
      public Builder setVersioncode(int value) {
        result.hasVersioncode = true;
        result.versioncode_ = value;
        return this;
      }
      public Builder clearVersioncode() {
        result.hasVersioncode = false;
        result.versioncode_ = 0;
        return this;
      }
      
      // optional string versionname = 5;
      public boolean hasVersionname() {
        return result.hasVersionname();
      }
      public java.lang.String getVersionname() {
        return result.getVersionname();
      }
      public Builder setVersionname(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasVersionname = true;
        result.versionname_ = value;
        return this;
      }
      public Builder clearVersionname() {
        result.hasVersionname = false;
        result.versionname_ = getDefaultInstance().getVersionname();
        return this;
      }
      
      // optional int32 ratecount = 6;
      public boolean hasRatecount() {
        return result.hasRatecount();
      }
      public int getRatecount() {
        return result.getRatecount();
      }
      public Builder setRatecount(int value) {
        result.hasRatecount = true;
        result.ratecount_ = value;
        return this;
      }
      public Builder clearRatecount() {
        result.hasRatecount = false;
        result.ratecount_ = 0;
        return this;
      }
      
      // optional double price = 7;
      public boolean hasPrice() {
        return result.hasPrice();
      }
      public double getPrice() {
        return result.getPrice();
      }
      public Builder setPrice(double value) {
        result.hasPrice = true;
        result.price_ = value;
        return this;
      }
      public Builder clearPrice() {
        result.hasPrice = false;
        result.price_ = 0D;
        return this;
      }
      
      // optional string priceUnit = 8;
      public boolean hasPriceUnit() {
        return result.hasPriceUnit();
      }
      public java.lang.String getPriceUnit() {
        return result.getPriceUnit();
      }
      public Builder setPriceUnit(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPriceUnit = true;
        result.priceUnit_ = value;
        return this;
      }
      public Builder clearPriceUnit() {
        result.hasPriceUnit = false;
        result.priceUnit_ = getDefaultInstance().getPriceUnit();
        return this;
      }
      
      // optional string description = 9;
      public boolean hasDescription() {
        return result.hasDescription();
      }
      public java.lang.String getDescription() {
        return result.getDescription();
      }
      public Builder setDescription(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDescription = true;
        result.description_ = value;
        return this;
      }
      public Builder clearDescription() {
        result.hasDescription = false;
        result.description_ = getDefaultInstance().getDescription();
        return this;
      }
      
      // optional int32 downloadsCount = 10;
      public boolean hasDownloadsCount() {
        return result.hasDownloadsCount();
      }
      public int getDownloadsCount() {
        return result.getDownloadsCount();
      }
      public Builder setDownloadsCount(int value) {
        result.hasDownloadsCount = true;
        result.downloadsCount_ = value;
        return this;
      }
      public Builder clearDownloadsCount() {
        result.hasDownloadsCount = false;
        result.downloadsCount_ = 0;
        return this;
      }
      
      // optional int32 lastmonth_downloadscount = 11;
      public boolean hasLastmonthDownloadscount() {
        return result.hasLastmonthDownloadscount();
      }
      public int getLastmonthDownloadscount() {
        return result.getLastmonthDownloadscount();
      }
      public Builder setLastmonthDownloadscount(int value) {
        result.hasLastmonthDownloadscount = true;
        result.lastmonthDownloadscount_ = value;
        return this;
      }
      public Builder clearLastmonthDownloadscount() {
        result.hasLastmonthDownloadscount = false;
        result.lastmonthDownloadscount_ = 0;
        return this;
      }
      
      // optional int32 lastweek_downloadscount = 12;
      public boolean hasLastweekDownloadscount() {
        return result.hasLastweekDownloadscount();
      }
      public int getLastweekDownloadscount() {
        return result.getLastweekDownloadscount();
      }
      public Builder setLastweekDownloadscount(int value) {
        result.hasLastweekDownloadscount = true;
        result.lastweekDownloadscount_ = value;
        return this;
      }
      public Builder clearLastweekDownloadscount() {
        result.hasLastweekDownloadscount = false;
        result.lastweekDownloadscount_ = 0;
        return this;
      }
      
      // optional int32 installSize = 13;
      public boolean hasInstallSize() {
        return result.hasInstallSize();
      }
      public int getInstallSize() {
        return result.getInstallSize();
      }
      public Builder setInstallSize(int value) {
        result.hasInstallSize = true;
        result.installSize_ = value;
        return this;
      }
      public Builder clearInstallSize() {
        result.hasInstallSize = false;
        result.installSize_ = 0;
        return this;
      }
      
      // optional string packageName = 14;
      public boolean hasPackageName() {
        return result.hasPackageName();
      }
      public java.lang.String getPackageName() {
        return result.getPackageName();
      }
      public Builder setPackageName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPackageName = true;
        result.packageName_ = value;
        return this;
      }
      public Builder clearPackageName() {
        result.hasPackageName = false;
        result.packageName_ = getDefaultInstance().getPackageName();
        return this;
      }
      
      // optional string category = 15;
      public boolean hasCategory() {
        return result.hasCategory();
      }
      public java.lang.String getCategory() {
        return result.getCategory();
      }
      public Builder setCategory(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCategory = true;
        result.category_ = value;
        return this;
      }
      public Builder clearCategory() {
        result.hasCategory = false;
        result.category_ = getDefaultInstance().getCategory();
        return this;
      }
      
      // optional int32 screenshotsCount = 16;
      public boolean hasScreenshotsCount() {
        return result.hasScreenshotsCount();
      }
      public int getScreenshotsCount() {
        return result.getScreenshotsCount();
      }
      public Builder setScreenshotsCount(int value) {
        result.hasScreenshotsCount = true;
        result.screenshotsCount_ = value;
        return this;
      }
      public Builder clearScreenshotsCount() {
        result.hasScreenshotsCount = false;
        result.screenshotsCount_ = 0;
        return this;
      }
      
      // optional string pathguid = 17;
      public boolean hasPathguid() {
        return result.hasPathguid();
      }
      public java.lang.String getPathguid() {
        return result.getPathguid();
      }
      public Builder setPathguid(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPathguid = true;
        result.pathguid_ = value;
        return this;
      }
      public Builder clearPathguid() {
        result.hasPathguid = false;
        result.pathguid_ = getDefaultInstance().getPathguid();
        return this;
      }
      
      // optional bytes iconData = 18;
      public boolean hasIconData() {
        return result.hasIconData();
      }
      public com.google.protobuf.ByteString getIconData() {
        return result.getIconData();
      }
      public Builder setIconData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasIconData = true;
        result.iconData_ = value;
        return this;
      }
      public Builder clearIconData() {
        result.hasIconData = false;
        result.iconData_ = getDefaultInstance().getIconData();
        return this;
      }
      
      // optional string downloadUrl = 19;
      public boolean hasDownloadUrl() {
        return result.hasDownloadUrl();
      }
      public java.lang.String getDownloadUrl() {
        return result.getDownloadUrl();
      }
      public Builder setDownloadUrl(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDownloadUrl = true;
        result.downloadUrl_ = value;
        return this;
      }
      public Builder clearDownloadUrl() {
        result.hasDownloadUrl = false;
        result.downloadUrl_ = getDefaultInstance().getDownloadUrl();
        return this;
      }
      
      // optional int32 partnerID = 20;
      public boolean hasPartnerID() {
        return result.hasPartnerID();
      }
      public int getPartnerID() {
        return result.getPartnerID();
      }
      public Builder setPartnerID(int value) {
        result.hasPartnerID = true;
        result.partnerID_ = value;
        return this;
      }
      public Builder clearPartnerID() {
        result.hasPartnerID = false;
        result.partnerID_ = 0;
        return this;
      }
      
      // optional int32 foreignID = 21;
      public boolean hasForeignID() {
        return result.hasForeignID();
      }
      public int getForeignID() {
        return result.getForeignID();
      }
      public Builder setForeignID(int value) {
        result.hasForeignID = true;
        result.foreignID_ = value;
        return this;
      }
      public Builder clearForeignID() {
        result.hasForeignID = false;
        result.foreignID_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.kindroid.security.util.App)
    }
    
    static {
      defaultInstance = new App(true);
      com.kindroid.security.util.AppProtoc.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.kindroid.security.util.App)
  }
  
  public static final class AppSearchRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use AppSearchRequest.newBuilder() to construct.
    private AppSearchRequest() {
      initFields();
    }
    private AppSearchRequest(boolean noInit) {}
    
    private static final AppSearchRequest defaultInstance;
    public static AppSearchRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public AppSearchRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kindroid.security.util.AppProtoc.internal_static_com_kindroid_security_util_AppSearchRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kindroid.security.util.AppProtoc.internal_static_com_kindroid_security_util_AppSearchRequest_fieldAccessorTable;
    }
    
    // optional string query = 1;
    public static final int QUERY_FIELD_NUMBER = 1;
    private boolean hasQuery;
    private java.lang.String query_ = "";
    public boolean hasQuery() { return hasQuery; }
    public java.lang.String getQuery() { return query_; }
    
    // optional string packagename = 2;
    public static final int PACKAGENAME_FIELD_NUMBER = 2;
    private boolean hasPackagename;
    private java.lang.String packagename_ = "";
    public boolean hasPackagename() { return hasPackagename; }
    public java.lang.String getPackagename() { return packagename_; }
    
    // optional int32 categoryID = 3;
    public static final int CATEGORYID_FIELD_NUMBER = 3;
    private boolean hasCategoryID;
    private int categoryID_ = 0;
    public boolean hasCategoryID() { return hasCategoryID; }
    public int getCategoryID() { return categoryID_; }
    
    // optional int32 appID = 4;
    public static final int APPID_FIELD_NUMBER = 4;
    private boolean hasAppID;
    private int appID_ = 0;
    public boolean hasAppID() { return hasAppID; }
    public int getAppID() { return appID_; }
    
    // optional int32 orderType = 6 [default = 0];
    public static final int ORDERTYPE_FIELD_NUMBER = 6;
    private boolean hasOrderType;
    private int orderType_ = 0;
    public boolean hasOrderType() { return hasOrderType; }
    public int getOrderType() { return orderType_; }
    
    // optional .com.kindroid.security.util.ViewType viewType = 7 [default = ALL_APP];
    public static final int VIEWTYPE_FIELD_NUMBER = 7;
    private boolean hasViewType;
    private com.kindroid.security.util.CommonProtoc.ViewType viewType_;
    public boolean hasViewType() { return hasViewType; }
    public com.kindroid.security.util.CommonProtoc.ViewType getViewType() { return viewType_; }
    
    // optional uint64 startIndex = 8;
    public static final int STARTINDEX_FIELD_NUMBER = 8;
    private boolean hasStartIndex;
    private long startIndex_ = 0L;
    public boolean hasStartIndex() { return hasStartIndex; }
    public long getStartIndex() { return startIndex_; }
    
    // optional int32 entriesCount = 9;
    public static final int ENTRIESCOUNT_FIELD_NUMBER = 9;
    private boolean hasEntriesCount;
    private int entriesCount_ = 0;
    public boolean hasEntriesCount() { return hasEntriesCount; }
    public int getEntriesCount() { return entriesCount_; }
    
    private void initFields() {
      viewType_ = com.kindroid.security.util.CommonProtoc.ViewType.ALL_APP;
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasQuery()) {
        output.writeString(1, getQuery());
      }
      if (hasPackagename()) {
        output.writeString(2, getPackagename());
      }
      if (hasCategoryID()) {
        output.writeInt32(3, getCategoryID());
      }
      if (hasAppID()) {
        output.writeInt32(4, getAppID());
      }
      if (hasOrderType()) {
        output.writeInt32(6, getOrderType());
      }
      if (hasViewType()) {
        output.writeEnum(7, getViewType().getNumber());
      }
      if (hasStartIndex()) {
        output.writeUInt64(8, getStartIndex());
      }
      if (hasEntriesCount()) {
        output.writeInt32(9, getEntriesCount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasQuery()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getQuery());
      }
      if (hasPackagename()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPackagename());
      }
      if (hasCategoryID()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getCategoryID());
      }
      if (hasAppID()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getAppID());
      }
      if (hasOrderType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, getOrderType());
      }
      if (hasViewType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, getViewType().getNumber());
      }
      if (hasStartIndex()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, getStartIndex());
      }
      if (hasEntriesCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, getEntriesCount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.kindroid.security.util.AppProtoc.AppSearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kindroid.security.util.AppProtoc.AppSearchRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.kindroid.security.util.AppProtoc.AppSearchRequest result;
      
      // Construct using com.kindroid.security.util.AppProtoc.AppSearchRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.kindroid.security.util.AppProtoc.AppSearchRequest();
        return builder;
      }
      
      protected com.kindroid.security.util.AppProtoc.AppSearchRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.kindroid.security.util.AppProtoc.AppSearchRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kindroid.security.util.AppProtoc.AppSearchRequest.getDescriptor();
      }
      
      public com.kindroid.security.util.AppProtoc.AppSearchRequest getDefaultInstanceForType() {
        return com.kindroid.security.util.AppProtoc.AppSearchRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.kindroid.security.util.AppProtoc.AppSearchRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.kindroid.security.util.AppProtoc.AppSearchRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.kindroid.security.util.AppProtoc.AppSearchRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.kindroid.security.util.AppProtoc.AppSearchRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kindroid.security.util.AppProtoc.AppSearchRequest) {
          return mergeFrom((com.kindroid.security.util.AppProtoc.AppSearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.kindroid.security.util.AppProtoc.AppSearchRequest other) {
        if (other == com.kindroid.security.util.AppProtoc.AppSearchRequest.getDefaultInstance()) return this;
        if (other.hasQuery()) {
          setQuery(other.getQuery());
        }
        if (other.hasPackagename()) {
          setPackagename(other.getPackagename());
        }
        if (other.hasCategoryID()) {
          setCategoryID(other.getCategoryID());
        }
        if (other.hasAppID()) {
          setAppID(other.getAppID());
        }
        if (other.hasOrderType()) {
          setOrderType(other.getOrderType());
        }
        if (other.hasViewType()) {
          setViewType(other.getViewType());
        }
        if (other.hasStartIndex()) {
          setStartIndex(other.getStartIndex());
        }
        if (other.hasEntriesCount()) {
          setEntriesCount(other.getEntriesCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setQuery(input.readString());
              break;
            }
            case 18: {
              setPackagename(input.readString());
              break;
            }
            case 24: {
              setCategoryID(input.readInt32());
              break;
            }
            case 32: {
              setAppID(input.readInt32());
              break;
            }
            case 48: {
              setOrderType(input.readInt32());
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              com.kindroid.security.util.CommonProtoc.ViewType value = com.kindroid.security.util.CommonProtoc.ViewType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                setViewType(value);
              }
              break;
            }
            case 64: {
              setStartIndex(input.readUInt64());
              break;
            }
            case 72: {
              setEntriesCount(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional string query = 1;
      public boolean hasQuery() {
        return result.hasQuery();
      }
      public java.lang.String getQuery() {
        return result.getQuery();
      }
      public Builder setQuery(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasQuery = true;
        result.query_ = value;
        return this;
      }
      public Builder clearQuery() {
        result.hasQuery = false;
        result.query_ = getDefaultInstance().getQuery();
        return this;
      }
      
      // optional string packagename = 2;
      public boolean hasPackagename() {
        return result.hasPackagename();
      }
      public java.lang.String getPackagename() {
        return result.getPackagename();
      }
      public Builder setPackagename(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPackagename = true;
        result.packagename_ = value;
        return this;
      }
      public Builder clearPackagename() {
        result.hasPackagename = false;
        result.packagename_ = getDefaultInstance().getPackagename();
        return this;
      }
      
      // optional int32 categoryID = 3;
      public boolean hasCategoryID() {
        return result.hasCategoryID();
      }
      public int getCategoryID() {
        return result.getCategoryID();
      }
      public Builder setCategoryID(int value) {
        result.hasCategoryID = true;
        result.categoryID_ = value;
        return this;
      }
      public Builder clearCategoryID() {
        result.hasCategoryID = false;
        result.categoryID_ = 0;
        return this;
      }
      
      // optional int32 appID = 4;
      public boolean hasAppID() {
        return result.hasAppID();
      }
      public int getAppID() {
        return result.getAppID();
      }
      public Builder setAppID(int value) {
        result.hasAppID = true;
        result.appID_ = value;
        return this;
      }
      public Builder clearAppID() {
        result.hasAppID = false;
        result.appID_ = 0;
        return this;
      }
      
      // optional int32 orderType = 6 [default = 0];
      public boolean hasOrderType() {
        return result.hasOrderType();
      }
      public int getOrderType() {
        return result.getOrderType();
      }
      public Builder setOrderType(int value) {
        result.hasOrderType = true;
        result.orderType_ = value;
        return this;
      }
      public Builder clearOrderType() {
        result.hasOrderType = false;
        result.orderType_ = 0;
        return this;
      }
      
      // optional .com.kindroid.security.util.ViewType viewType = 7 [default = ALL_APP];
      public boolean hasViewType() {
        return result.hasViewType();
      }
      public com.kindroid.security.util.CommonProtoc.ViewType getViewType() {
        return result.getViewType();
      }
      public Builder setViewType(com.kindroid.security.util.CommonProtoc.ViewType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasViewType = true;
        result.viewType_ = value;
        return this;
      }
      public Builder clearViewType() {
        result.hasViewType = false;
        result.viewType_ = com.kindroid.security.util.CommonProtoc.ViewType.ALL_APP;
        return this;
      }
      
      // optional uint64 startIndex = 8;
      public boolean hasStartIndex() {
        return result.hasStartIndex();
      }
      public long getStartIndex() {
        return result.getStartIndex();
      }
      public Builder setStartIndex(long value) {
        result.hasStartIndex = true;
        result.startIndex_ = value;
        return this;
      }
      public Builder clearStartIndex() {
        result.hasStartIndex = false;
        result.startIndex_ = 0L;
        return this;
      }
      
      // optional int32 entriesCount = 9;
      public boolean hasEntriesCount() {
        return result.hasEntriesCount();
      }
      public int getEntriesCount() {
        return result.getEntriesCount();
      }
      public Builder setEntriesCount(int value) {
        result.hasEntriesCount = true;
        result.entriesCount_ = value;
        return this;
      }
      public Builder clearEntriesCount() {
        result.hasEntriesCount = false;
        result.entriesCount_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.kindroid.security.util.AppSearchRequest)
    }
    
    static {
      defaultInstance = new AppSearchRequest(true);
      com.kindroid.security.util.AppProtoc.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.kindroid.security.util.AppSearchRequest)
  }
  
  public static final class AppSearchResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use AppSearchResponse.newBuilder() to construct.
    private AppSearchResponse() {
      initFields();
    }
    private AppSearchResponse(boolean noInit) {}
    
    private static final AppSearchResponse defaultInstance;
    public static AppSearchResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public AppSearchResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kindroid.security.util.AppProtoc.internal_static_com_kindroid_security_util_AppSearchResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kindroid.security.util.AppProtoc.internal_static_com_kindroid_security_util_AppSearchResponse_fieldAccessorTable;
    }
    
    // repeated .com.kindroid.security.util.App app = 1;
    public static final int APP_FIELD_NUMBER = 1;
    private java.util.List<com.kindroid.security.util.AppProtoc.App> app_ =
      java.util.Collections.emptyList();
    public java.util.List<com.kindroid.security.util.AppProtoc.App> getAppList() {
      return app_;
    }
    public int getAppCount() { return app_.size(); }
    public com.kindroid.security.util.AppProtoc.App getApp(int index) {
      return app_.get(index);
    }
    
    // optional int32 entriesCount = 2;
    public static final int ENTRIESCOUNT_FIELD_NUMBER = 2;
    private boolean hasEntriesCount;
    private int entriesCount_ = 0;
    public boolean hasEntriesCount() { return hasEntriesCount; }
    public int getEntriesCount() { return entriesCount_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.kindroid.security.util.AppProtoc.App element : getAppList()) {
        output.writeMessage(1, element);
      }
      if (hasEntriesCount()) {
        output.writeInt32(2, getEntriesCount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.kindroid.security.util.AppProtoc.App element : getAppList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      if (hasEntriesCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getEntriesCount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.kindroid.security.util.AppProtoc.AppSearchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.security.util.AppProtoc.AppSearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kindroid.security.util.AppProtoc.AppSearchResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.kindroid.security.util.AppProtoc.AppSearchResponse result;
      
      // Construct using com.kindroid.security.util.AppProtoc.AppSearchResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.kindroid.security.util.AppProtoc.AppSearchResponse();
        return builder;
      }
      
      protected com.kindroid.security.util.AppProtoc.AppSearchResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.kindroid.security.util.AppProtoc.AppSearchResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kindroid.security.util.AppProtoc.AppSearchResponse.getDescriptor();
      }
      
      public com.kindroid.security.util.AppProtoc.AppSearchResponse getDefaultInstanceForType() {
        return com.kindroid.security.util.AppProtoc.AppSearchResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.kindroid.security.util.AppProtoc.AppSearchResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.kindroid.security.util.AppProtoc.AppSearchResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.kindroid.security.util.AppProtoc.AppSearchResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.app_ != java.util.Collections.EMPTY_LIST) {
          result.app_ =
            java.util.Collections.unmodifiableList(result.app_);
        }
        com.kindroid.security.util.AppProtoc.AppSearchResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kindroid.security.util.AppProtoc.AppSearchResponse) {
          return mergeFrom((com.kindroid.security.util.AppProtoc.AppSearchResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.kindroid.security.util.AppProtoc.AppSearchResponse other) {
        if (other == com.kindroid.security.util.AppProtoc.AppSearchResponse.getDefaultInstance()) return this;
        if (!other.app_.isEmpty()) {
          if (result.app_.isEmpty()) {
            result.app_ = new java.util.ArrayList<com.kindroid.security.util.AppProtoc.App>();
          }
          result.app_.addAll(other.app_);
        }
        if (other.hasEntriesCount()) {
          setEntriesCount(other.getEntriesCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.kindroid.security.util.AppProtoc.App.Builder subBuilder = com.kindroid.security.util.AppProtoc.App.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addApp(subBuilder.buildPartial());
              break;
            }
            case 16: {
              setEntriesCount(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.kindroid.security.util.App app = 1;
      public java.util.List<com.kindroid.security.util.AppProtoc.App> getAppList() {
        return java.util.Collections.unmodifiableList(result.app_);
      }
      public int getAppCount() {
        return result.getAppCount();
      }
      public com.kindroid.security.util.AppProtoc.App getApp(int index) {
        return result.getApp(index);
      }
      public Builder setApp(int index, com.kindroid.security.util.AppProtoc.App value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.app_.set(index, value);
        return this;
      }
      public Builder setApp(int index, com.kindroid.security.util.AppProtoc.App.Builder builderForValue) {
        result.app_.set(index, builderForValue.build());
        return this;
      }
      public Builder addApp(com.kindroid.security.util.AppProtoc.App value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.app_.isEmpty()) {
          result.app_ = new java.util.ArrayList<com.kindroid.security.util.AppProtoc.App>();
        }
        result.app_.add(value);
        return this;
      }
      public Builder addApp(com.kindroid.security.util.AppProtoc.App.Builder builderForValue) {
        if (result.app_.isEmpty()) {
          result.app_ = new java.util.ArrayList<com.kindroid.security.util.AppProtoc.App>();
        }
        result.app_.add(builderForValue.build());
        return this;
      }
      public Builder addAllApp(
          java.lang.Iterable<? extends com.kindroid.security.util.AppProtoc.App> values) {
        if (result.app_.isEmpty()) {
          result.app_ = new java.util.ArrayList<com.kindroid.security.util.AppProtoc.App>();
        }
        super.addAll(values, result.app_);
        return this;
      }
      public Builder clearApp() {
        result.app_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional int32 entriesCount = 2;
      public boolean hasEntriesCount() {
        return result.hasEntriesCount();
      }
      public int getEntriesCount() {
        return result.getEntriesCount();
      }
      public Builder setEntriesCount(int value) {
        result.hasEntriesCount = true;
        result.entriesCount_ = value;
        return this;
      }
      public Builder clearEntriesCount() {
        result.hasEntriesCount = false;
        result.entriesCount_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.kindroid.security.util.AppSearchResponse)
    }
    
    static {
      defaultInstance = new AppSearchResponse(true);
      com.kindroid.security.util.AppProtoc.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.kindroid.security.util.AppSearchResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kindroid_security_util_App_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kindroid_security_util_App_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kindroid_security_util_AppSearchRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kindroid_security_util_AppSearchRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kindroid_security_util_AppSearchResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kindroid_security_util_AppSearchResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017AppProtoc.proto\022\032com.kindroid.security" +
      ".util\032\022CommonProtoc.proto\"\264\003\n\003App\022\n\n\002id\030" +
      "\001 \001(\005\022\r\n\005title\030\002 \001(\t\022\016\n\006author\030\003 \001(\t\022\023\n\013" +
      "versioncode\030\004 \001(\005\022\023\n\013versionname\030\005 \001(\t\022\021" +
      "\n\tratecount\030\006 \001(\005\022\r\n\005price\030\007 \001(\001\022\021\n\tpric" +
      "eUnit\030\010 \001(\t\022\023\n\013description\030\t \001(\t\022\026\n\016down" +
      "loadsCount\030\n \001(\005\022 \n\030lastmonth_downloadsc" +
      "ount\030\013 \001(\005\022\037\n\027lastweek_downloadscount\030\014 " +
      "\001(\005\022\023\n\013installSize\030\r \001(\005\022\023\n\013packageName\030" +
      "\016 \001(\t\022\020\n\010category\030\017 \001(\t\022\030\n\020screenshotsCo",
      "unt\030\020 \001(\005\022\020\n\010pathguid\030\021 \001(\t\022\020\n\010iconData\030" +
      "\022 \001(\014\022\023\n\013downloadUrl\030\023 \001(\t\022\021\n\tpartnerID\030" +
      "\024 \001(\005\022\021\n\tforeignID\030\025 \001(\005\"\332\001\n\020AppSearchRe" +
      "quest\022\r\n\005query\030\001 \001(\t\022\023\n\013packagename\030\002 \001(" +
      "\t\022\022\n\ncategoryID\030\003 \001(\005\022\r\n\005appID\030\004 \001(\005\022\024\n\t" +
      "orderType\030\006 \001(\005:\0010\022?\n\010viewType\030\007 \001(\0162$.c" +
      "om.kindroid.security.util.ViewType:\007ALL_" +
      "APP\022\022\n\nstartIndex\030\010 \001(\004\022\024\n\014entriesCount\030" +
      "\t \001(\005\"W\n\021AppSearchResponse\022,\n\003app\030\001 \003(\0132" +
      "\037.com.kindroid.security.util.App\022\024\n\014entr",
      "iesCount\030\002 \001(\005B\034\n\032com.kindroid.security." +
      "util"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_kindroid_security_util_App_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_kindroid_security_util_App_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_kindroid_security_util_App_descriptor,
              new java.lang.String[] { "Id", "Title", "Author", "Versioncode", "Versionname", "Ratecount", "Price", "PriceUnit", "Description", "DownloadsCount", "LastmonthDownloadscount", "LastweekDownloadscount", "InstallSize", "PackageName", "Category", "ScreenshotsCount", "Pathguid", "IconData", "DownloadUrl", "PartnerID", "ForeignID", },
              com.kindroid.security.util.AppProtoc.App.class,
              com.kindroid.security.util.AppProtoc.App.Builder.class);
          internal_static_com_kindroid_security_util_AppSearchRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_kindroid_security_util_AppSearchRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_kindroid_security_util_AppSearchRequest_descriptor,
              new java.lang.String[] { "Query", "Packagename", "CategoryID", "AppID", "OrderType", "ViewType", "StartIndex", "EntriesCount", },
              com.kindroid.security.util.AppProtoc.AppSearchRequest.class,
              com.kindroid.security.util.AppProtoc.AppSearchRequest.Builder.class);
          internal_static_com_kindroid_security_util_AppSearchResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_kindroid_security_util_AppSearchResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_kindroid_security_util_AppSearchResponse_descriptor,
              new java.lang.String[] { "App", "EntriesCount", },
              com.kindroid.security.util.AppProtoc.AppSearchResponse.class,
              com.kindroid.security.util.AppProtoc.AppSearchResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kindroid.security.util.CommonProtoc.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
