// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmailProtoc.proto

package com.kindroid.security.util;

public final class EmailProtoc {
  private EmailProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Email extends
      com.google.protobuf.GeneratedMessage {
    // Use Email.newBuilder() to construct.
    private Email() {
      initFields();
    }
    private Email(boolean noInit) {}
    
    private static final Email defaultInstance;
    public static Email getDefaultInstance() {
      return defaultInstance;
    }
    
    public Email getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kindroid.security.util.EmailProtoc.internal_static_com_kindroid_security_util_Email_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kindroid.security.util.EmailProtoc.internal_static_com_kindroid_security_util_Email_fieldAccessorTable;
    }
    
    // required string receiver = 1;
    public static final int RECEIVER_FIELD_NUMBER = 1;
    private boolean hasReceiver;
    private java.lang.String receiver_ = "";
    public boolean hasReceiver() { return hasReceiver; }
    public java.lang.String getReceiver() { return receiver_; }
    
    // required .com.kindroid.security.util.EmailType emailType = 2;
    public static final int EMAILTYPE_FIELD_NUMBER = 2;
    private boolean hasEmailType;
    private com.kindroid.security.util.CommonProtoc.EmailType emailType_;
    public boolean hasEmailType() { return hasEmailType; }
    public com.kindroid.security.util.CommonProtoc.EmailType getEmailType() { return emailType_; }
    
    // optional string sender = 3;
    public static final int SENDER_FIELD_NUMBER = 3;
    private boolean hasSender;
    private java.lang.String sender_ = "";
    public boolean hasSender() { return hasSender; }
    public java.lang.String getSender() { return sender_; }
    
    // optional string content = 4;
    public static final int CONTENT_FIELD_NUMBER = 4;
    private boolean hasContent;
    private java.lang.String content_ = "";
    public boolean hasContent() { return hasContent; }
    public java.lang.String getContent() { return content_; }
    
    private void initFields() {
      emailType_ = com.kindroid.security.util.CommonProtoc.EmailType.OTHER_EMAIL;
    }
    public final boolean isInitialized() {
      if (!hasReceiver) return false;
      if (!hasEmailType) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasReceiver()) {
        output.writeString(1, getReceiver());
      }
      if (hasEmailType()) {
        output.writeEnum(2, getEmailType().getNumber());
      }
      if (hasSender()) {
        output.writeString(3, getSender());
      }
      if (hasContent()) {
        output.writeString(4, getContent());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasReceiver()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getReceiver());
      }
      if (hasEmailType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, getEmailType().getNumber());
      }
      if (hasSender()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getSender());
      }
      if (hasContent()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getContent());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.kindroid.security.util.EmailProtoc.Email parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.Email parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.Email parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.Email parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.Email parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.Email parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.Email parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.security.util.EmailProtoc.Email parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.security.util.EmailProtoc.Email parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.Email parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kindroid.security.util.EmailProtoc.Email prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.kindroid.security.util.EmailProtoc.Email result;
      
      // Construct using com.kindroid.security.util.EmailProtoc.Email.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.kindroid.security.util.EmailProtoc.Email();
        return builder;
      }
      
      protected com.kindroid.security.util.EmailProtoc.Email internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.kindroid.security.util.EmailProtoc.Email();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kindroid.security.util.EmailProtoc.Email.getDescriptor();
      }
      
      public com.kindroid.security.util.EmailProtoc.Email getDefaultInstanceForType() {
        return com.kindroid.security.util.EmailProtoc.Email.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.kindroid.security.util.EmailProtoc.Email build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.kindroid.security.util.EmailProtoc.Email buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.kindroid.security.util.EmailProtoc.Email buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.kindroid.security.util.EmailProtoc.Email returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kindroid.security.util.EmailProtoc.Email) {
          return mergeFrom((com.kindroid.security.util.EmailProtoc.Email)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.kindroid.security.util.EmailProtoc.Email other) {
        if (other == com.kindroid.security.util.EmailProtoc.Email.getDefaultInstance()) return this;
        if (other.hasReceiver()) {
          setReceiver(other.getReceiver());
        }
        if (other.hasEmailType()) {
          setEmailType(other.getEmailType());
        }
        if (other.hasSender()) {
          setSender(other.getSender());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setReceiver(input.readString());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.kindroid.security.util.CommonProtoc.EmailType value = com.kindroid.security.util.CommonProtoc.EmailType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                setEmailType(value);
              }
              break;
            }
            case 26: {
              setSender(input.readString());
              break;
            }
            case 34: {
              setContent(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string receiver = 1;
      public boolean hasReceiver() {
        return result.hasReceiver();
      }
      public java.lang.String getReceiver() {
        return result.getReceiver();
      }
      public Builder setReceiver(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasReceiver = true;
        result.receiver_ = value;
        return this;
      }
      public Builder clearReceiver() {
        result.hasReceiver = false;
        result.receiver_ = getDefaultInstance().getReceiver();
        return this;
      }
      
      // required .com.kindroid.security.util.EmailType emailType = 2;
      public boolean hasEmailType() {
        return result.hasEmailType();
      }
      public com.kindroid.security.util.CommonProtoc.EmailType getEmailType() {
        return result.getEmailType();
      }
      public Builder setEmailType(com.kindroid.security.util.CommonProtoc.EmailType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasEmailType = true;
        result.emailType_ = value;
        return this;
      }
      public Builder clearEmailType() {
        result.hasEmailType = false;
        result.emailType_ = com.kindroid.security.util.CommonProtoc.EmailType.OTHER_EMAIL;
        return this;
      }
      
      // optional string sender = 3;
      public boolean hasSender() {
        return result.hasSender();
      }
      public java.lang.String getSender() {
        return result.getSender();
      }
      public Builder setSender(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSender = true;
        result.sender_ = value;
        return this;
      }
      public Builder clearSender() {
        result.hasSender = false;
        result.sender_ = getDefaultInstance().getSender();
        return this;
      }
      
      // optional string content = 4;
      public boolean hasContent() {
        return result.hasContent();
      }
      public java.lang.String getContent() {
        return result.getContent();
      }
      public Builder setContent(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasContent = true;
        result.content_ = value;
        return this;
      }
      public Builder clearContent() {
        result.hasContent = false;
        result.content_ = getDefaultInstance().getContent();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.kindroid.security.util.Email)
    }
    
    static {
      defaultInstance = new Email(true);
      com.kindroid.security.util.EmailProtoc.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.kindroid.security.util.Email)
  }
  
  public static final class EmailRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use EmailRequest.newBuilder() to construct.
    private EmailRequest() {
      initFields();
    }
    private EmailRequest(boolean noInit) {}
    
    private static final EmailRequest defaultInstance;
    public static EmailRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public EmailRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kindroid.security.util.EmailProtoc.internal_static_com_kindroid_security_util_EmailRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kindroid.security.util.EmailProtoc.internal_static_com_kindroid_security_util_EmailRequest_fieldAccessorTable;
    }
    
    // required .com.kindroid.security.util.Email email = 1;
    public static final int EMAIL_FIELD_NUMBER = 1;
    private boolean hasEmail;
    private com.kindroid.security.util.EmailProtoc.Email email_;
    public boolean hasEmail() { return hasEmail; }
    public com.kindroid.security.util.EmailProtoc.Email getEmail() { return email_; }
    
    // optional string safePhone = 2;
    public static final int SAFEPHONE_FIELD_NUMBER = 2;
    private boolean hasSafePhone;
    private java.lang.String safePhone_ = "";
    public boolean hasSafePhone() { return hasSafePhone; }
    public java.lang.String getSafePhone() { return safePhone_; }
    
    private void initFields() {
      email_ = com.kindroid.security.util.EmailProtoc.Email.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasEmail) return false;
      if (!getEmail().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasEmail()) {
        output.writeMessage(1, getEmail());
      }
      if (hasSafePhone()) {
        output.writeString(2, getSafePhone());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasEmail()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getEmail());
      }
      if (hasSafePhone()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getSafePhone());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.kindroid.security.util.EmailProtoc.EmailRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.EmailRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.EmailRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.EmailRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.EmailRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.EmailRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.EmailRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.security.util.EmailProtoc.EmailRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.security.util.EmailProtoc.EmailRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.EmailRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kindroid.security.util.EmailProtoc.EmailRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.kindroid.security.util.EmailProtoc.EmailRequest result;
      
      // Construct using com.kindroid.security.util.EmailProtoc.EmailRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.kindroid.security.util.EmailProtoc.EmailRequest();
        return builder;
      }
      
      protected com.kindroid.security.util.EmailProtoc.EmailRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.kindroid.security.util.EmailProtoc.EmailRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kindroid.security.util.EmailProtoc.EmailRequest.getDescriptor();
      }
      
      public com.kindroid.security.util.EmailProtoc.EmailRequest getDefaultInstanceForType() {
        return com.kindroid.security.util.EmailProtoc.EmailRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.kindroid.security.util.EmailProtoc.EmailRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.kindroid.security.util.EmailProtoc.EmailRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.kindroid.security.util.EmailProtoc.EmailRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.kindroid.security.util.EmailProtoc.EmailRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kindroid.security.util.EmailProtoc.EmailRequest) {
          return mergeFrom((com.kindroid.security.util.EmailProtoc.EmailRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.kindroid.security.util.EmailProtoc.EmailRequest other) {
        if (other == com.kindroid.security.util.EmailProtoc.EmailRequest.getDefaultInstance()) return this;
        if (other.hasEmail()) {
          mergeEmail(other.getEmail());
        }
        if (other.hasSafePhone()) {
          setSafePhone(other.getSafePhone());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.kindroid.security.util.EmailProtoc.Email.Builder subBuilder = com.kindroid.security.util.EmailProtoc.Email.newBuilder();
              if (hasEmail()) {
                subBuilder.mergeFrom(getEmail());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setEmail(subBuilder.buildPartial());
              break;
            }
            case 18: {
              setSafePhone(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required .com.kindroid.security.util.Email email = 1;
      public boolean hasEmail() {
        return result.hasEmail();
      }
      public com.kindroid.security.util.EmailProtoc.Email getEmail() {
        return result.getEmail();
      }
      public Builder setEmail(com.kindroid.security.util.EmailProtoc.Email value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasEmail = true;
        result.email_ = value;
        return this;
      }
      public Builder setEmail(com.kindroid.security.util.EmailProtoc.Email.Builder builderForValue) {
        result.hasEmail = true;
        result.email_ = builderForValue.build();
        return this;
      }
      public Builder mergeEmail(com.kindroid.security.util.EmailProtoc.Email value) {
        if (result.hasEmail() &&
            result.email_ != com.kindroid.security.util.EmailProtoc.Email.getDefaultInstance()) {
          result.email_ =
            com.kindroid.security.util.EmailProtoc.Email.newBuilder(result.email_).mergeFrom(value).buildPartial();
        } else {
          result.email_ = value;
        }
        result.hasEmail = true;
        return this;
      }
      public Builder clearEmail() {
        result.hasEmail = false;
        result.email_ = com.kindroid.security.util.EmailProtoc.Email.getDefaultInstance();
        return this;
      }
      
      // optional string safePhone = 2;
      public boolean hasSafePhone() {
        return result.hasSafePhone();
      }
      public java.lang.String getSafePhone() {
        return result.getSafePhone();
      }
      public Builder setSafePhone(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSafePhone = true;
        result.safePhone_ = value;
        return this;
      }
      public Builder clearSafePhone() {
        result.hasSafePhone = false;
        result.safePhone_ = getDefaultInstance().getSafePhone();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.kindroid.security.util.EmailRequest)
    }
    
    static {
      defaultInstance = new EmailRequest(true);
      com.kindroid.security.util.EmailProtoc.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.kindroid.security.util.EmailRequest)
  }
  
  public static final class EmailResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use EmailResponse.newBuilder() to construct.
    private EmailResponse() {
      initFields();
    }
    private EmailResponse(boolean noInit) {}
    
    private static final EmailResponse defaultInstance;
    public static EmailResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public EmailResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kindroid.security.util.EmailProtoc.internal_static_com_kindroid_security_util_EmailResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kindroid.security.util.EmailProtoc.internal_static_com_kindroid_security_util_EmailResponse_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.kindroid.security.util.EmailProtoc.EmailResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.EmailResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.EmailResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.EmailResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.EmailResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.EmailResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.EmailResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.security.util.EmailProtoc.EmailResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.kindroid.security.util.EmailProtoc.EmailResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.kindroid.security.util.EmailProtoc.EmailResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kindroid.security.util.EmailProtoc.EmailResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.kindroid.security.util.EmailProtoc.EmailResponse result;
      
      // Construct using com.kindroid.security.util.EmailProtoc.EmailResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.kindroid.security.util.EmailProtoc.EmailResponse();
        return builder;
      }
      
      protected com.kindroid.security.util.EmailProtoc.EmailResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.kindroid.security.util.EmailProtoc.EmailResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kindroid.security.util.EmailProtoc.EmailResponse.getDescriptor();
      }
      
      public com.kindroid.security.util.EmailProtoc.EmailResponse getDefaultInstanceForType() {
        return com.kindroid.security.util.EmailProtoc.EmailResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.kindroid.security.util.EmailProtoc.EmailResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.kindroid.security.util.EmailProtoc.EmailResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.kindroid.security.util.EmailProtoc.EmailResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.kindroid.security.util.EmailProtoc.EmailResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kindroid.security.util.EmailProtoc.EmailResponse) {
          return mergeFrom((com.kindroid.security.util.EmailProtoc.EmailResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.kindroid.security.util.EmailProtoc.EmailResponse other) {
        if (other == com.kindroid.security.util.EmailProtoc.EmailResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.kindroid.security.util.EmailResponse)
    }
    
    static {
      defaultInstance = new EmailResponse(true);
      com.kindroid.security.util.EmailProtoc.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.kindroid.security.util.EmailResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kindroid_security_util_Email_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kindroid_security_util_Email_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kindroid_security_util_EmailRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kindroid_security_util_EmailRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kindroid_security_util_EmailResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kindroid_security_util_EmailResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021EmailProtoc.proto\022\032com.kindroid.securi" +
      "ty.util\032\022CommonProtoc.proto\"t\n\005Email\022\020\n\010" +
      "receiver\030\001 \002(\t\0228\n\temailType\030\002 \002(\0162%.com." +
      "kindroid.security.util.EmailType\022\016\n\006send" +
      "er\030\003 \001(\t\022\017\n\007content\030\004 \001(\t\"S\n\014EmailReques" +
      "t\0220\n\005email\030\001 \002(\0132!.com.kindroid.security" +
      ".util.Email\022\021\n\tsafePhone\030\002 \001(\t\"\017\n\rEmailR" +
      "esponseB\034\n\032com.kindroid.security.util"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_kindroid_security_util_Email_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_kindroid_security_util_Email_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_kindroid_security_util_Email_descriptor,
              new java.lang.String[] { "Receiver", "EmailType", "Sender", "Content", },
              com.kindroid.security.util.EmailProtoc.Email.class,
              com.kindroid.security.util.EmailProtoc.Email.Builder.class);
          internal_static_com_kindroid_security_util_EmailRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_kindroid_security_util_EmailRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_kindroid_security_util_EmailRequest_descriptor,
              new java.lang.String[] { "Email", "SafePhone", },
              com.kindroid.security.util.EmailProtoc.EmailRequest.class,
              com.kindroid.security.util.EmailProtoc.EmailRequest.Builder.class);
          internal_static_com_kindroid_security_util_EmailResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_kindroid_security_util_EmailResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_kindroid_security_util_EmailResponse_descriptor,
              new java.lang.String[] { },
              com.kindroid.security.util.EmailProtoc.EmailResponse.class,
              com.kindroid.security.util.EmailProtoc.EmailResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kindroid.security.util.CommonProtoc.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
